export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userConstants = {
  USER_REGISTRATION_REQUEST: " USER_REGISTRATION_REQUEST",
  USER_REGISTRATION_SUCCESS: " USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: " USER_REGISTRATION_FAILURE",
};
export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: " ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  UPDATE_CATEGORY_REQUEST: " UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_SUCCESS: " UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: " UPDATE_CATEGORY_FAILURE",
  DELETE_CATEGORY_REQUEST: " DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: " DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: " DELETE_CATEGORY_FAILURE",
};
export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
};
